#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Feb 09, 2020 02:04:18 PM +0200  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+650+150
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background #ff62b0 -height 365 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 445 
    vTcl:DefineAlias "$top.fra43" "open_frame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    label $site_3_0.lab44 \
        -activebackground #f9f9f9 -activeforeground #000000 \
        -background #ffb0d8 -disabledforeground #a3a3a3 \
        -font {-family {Tw Cen MT} -size 24 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Choose an option} 
    vTcl:DefineAlias "$site_3_0.lab44" "title_label" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Tw Cen MT} -size 22 -weight bold} -foreground #ffb0d8 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor #ffffff \
        -pady 0 -text Instructions 
    vTcl:DefineAlias "$site_3_0.but45" "instr_button" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #ffb0d8 \
        -font {-family {Tw Cen MT} -size 22 -weight bold} -foreground #ffb0d8 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Login 
    vTcl:DefineAlias "$site_3_0.but46" "login_bottun" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab44 \
        -in $site_3_0 -x 10 -y 10 -width 424 -relwidth 0 -height 71 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 70 -y 120 -width 311 -relwidth 0 -height 94 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 70 -y 230 -width 307 -relwidth 0 -height 94 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 60 -y 30 -width 445 -relwidth 0 -height 365 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

