#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Feb 06, 2020 12:43:50 PM +0200  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 659x450+1014+246
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra55 \
        -borderwidth 2 -relief groove -background #b366ff -height 395 \
        -highlightbackground #690f96 -highlightcolor #690f96 -width 495 
    vTcl:DefineAlias "$top.fra55" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra55
    ttk::label $site_3_0.tLa58 \
        -background #690f96 -foreground #ffffff \
        -font {-family {Levenim MT} -size 13 -weight bold} -relief flat \
        -text {please enter your username and your password} 
    vTcl:DefineAlias "$site_3_0.tLa58" "instruction" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent59 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent59" "entry_username" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #690f96 -disabledforeground #a3a3a3 \
        -font {-family {Levenim MT} -size 12 -weight bold} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text Login 
    vTcl:DefineAlias "$site_3_0.but60" "login" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but60 <Button-1> {
        lambda e: xxx(e)
    }
    label $site_3_0.lab65 \
        -activebackground #690f96 -activeforeground #000000 \
        -background #690f96 -disabledforeground #a3a3a3 \
        -font {-family {Levenim MT} -size 9 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text username 
    vTcl:DefineAlias "$site_3_0.lab65" "Label_username" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent66 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent66" "entry_password" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab67 \
        -activebackground #f9f9f9 -activeforeground black -background #690f96 \
        -disabledforeground #a3a3a3 \
        -font {-family {Levenim MT} -size 9 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text password 
    vTcl:DefineAlias "$site_3_0.lab67" "Label_password" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tLa58 \
        -in $site_3_0 -x 40 -y 40 -width 416 -relwidth 0 -height 59 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent59 \
        -in $site_3_0 -x 160 -y 140 -width 174 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but60 \
        -in $site_3_0 -x 310 -y 300 -width 107 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 60 -y 140 -width 84 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent66 \
        -in $site_3_0 -x 160 -y 200 -width 174 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 60 -y 200 -width 84 -height 31 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra55 \
        -in $top -x 120 -y 30 -width 495 -relwidth 0 -height 395 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

